---
title: "hw5"
author: "C-T Berezin"
date: "11/15/2021"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(tidyverse)
library(lubridate)
```

```{r}
#read in the data
homicides <- read.csv("../data/homicide-data.csv")
```

```{r}
#update the date columns
homicides <- homicides %>% 
  mutate(reported_date = ymd(reported_date),
         month = month(reported_date, label=TRUE)) %>%
  mutate(year_mo = format(as.Date(reported_date), "%Y-%m"),
         warm_mo = month %in% c("May", "Jun", "Jul", "Aug", "Sep", "Oct")) %>% 
  mutate(year_mo = ym(year_mo),
         season = fct_recode(as.factor(warm_mo),
                              Summer = "TRUE",
                              Winter = "FALSE"))
```

```{r}
#filter to just Baltimore
balt_homs <- homicides %>% 
  unite("Location", city:state, sep=", ") %>% 
  filter(Location == "Baltimore, MD")
```

```{r}
#count up monthly homicides in Baltimore
monthly_homs <- balt_homs %>% group_by(year_mo, season) %>% count()
```

```{r}
#save the date of Freddie Gray's arrest
arrest <- as.Date("2015-04-12")
```

```{r, fig.height=3, fig.width=10}
#plot the data
plot <- ggplot(monthly_homs, aes(x=year_mo, y=n)) +
  geom_col(aes(fill=factor(season, levels=c("Summer", "Winter")))) +
  scale_x_date(name = "Date",
               date_labels = "%Y") +
  geom_vline(xintercept = arrest,
             linetype = "dashed",
             col = "red",
             size=1.5) +
  geom_text(aes(x=arrest, y=40),
            label="Arrest of\nFreddie Gray",
            hjust=1,
            nudge_x=-30,
            col = "white",
            check_overlap = TRUE) +
  labs(title = "Homicides in Baltimore, MD",
       y = "Monthly Homicides") +
  theme_dark() +
  theme(legend.title = element_blank(),
        legend.position="bottom") +
  scale_fill_manual(values = c("grey80", "lightblue")) +
  geom_smooth(method="loess", span=0.1, se=FALSE)
plot
```

```{r}
#save the plot
ggsave("../figures/balt_monthly_homs.png", plot = plot, height=3, width=10)
```

